feat: listen content changes of nodes
CanCLID/inject-jyutping pull request #1
Opened 2021-12-07 12:36 UTC by ambar

- 监听节点的新增和内容变化（通过 `MutationObserver`）
- 删除了节点的 `lang` 属性检测，我猜这没有用处，因为即使母语是日语，网页同样可以嵌入中文内容（以便进行学习）
- MessageManager 中防止实例 id 冲突
- popup 中标签避免折行

2021-12-07 15:21 UTC, laubonghaudoi commented
@ambar 唔係好明點解要刪個`lang`檢測，我嘅理解係如果係日語頁面就冇必要再標粵拼，因為冇人會用粵語發音讀啲日語漢字。@ayaka14732 你點諗？

2021-12-07 15:25 UTC, laubonghaudoi approved these changes

2021-12-07 15:27 UTC, laubonghaudoi commented on content_scripts/main.js
> +    return reHan.test(s);
如果係改成噉，就即係只要係漢字都自動加粵拼？我冇意見，睇 @ayaka14732

2021-12-07 15:29 UTC, laubonghaudoi requested changes
多謝貢獻，不過可唔可以順便更新埋個版本號？如果合併咗呢個就會係個 0.2.6 版

2021-12-07 15:42 UTC, ayaka14732 commented
> 多謝貢獻，不過可唔可以順便更新埋個版本號？如果合併咗呢個就會係個 0.2.6 版

PR 入面唔應該更新版本號，發佈嗰陣我嚟更新

2021-12-07 15:51 UTC, graphemecluster commented
不過 @ambar 嘅 concern 似乎係好多網站會錯標或者漏標 `lang` attribute

2021-12-07 15:55 UTC, ayaka14732 commented on content_scripts/main.js
> +    return reHan.test(s);
同意，應該分拆成兩個 PR，一個 PR 凈係做一樣嘢，便於 review

2021-12-07 15:57 UTC, graphemecluster commented on content_scripts/main.js
> +    if (['RUBY', 'RP', 'RT', 'OPTION', 'TEXTAREA', 'SCRIPT', 'STYLE'].includes(node.parentNode.nodeName)) {
同埋最好遞迴檢測 parent node（速度又係另一個問題），因為個 spec 規定唔喺 `ruby` 入面嘅 `rp` `rt` 同通常嘅 element 冇分別

如果唔係就要加埋 `SELECT`

2021-12-07 16:00 UTC, graphemecluster commented on content_scripts/main.js
> +    const treeWalker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
其實係咪應該用第三個參數 NodeFilter？

2021-12-07 16:42 UTC, laubonghaudoi commented
> > 多謝貢獻，不過可唔可以順便更新埋個版本號？如果合併咗呢個就會係個 0.2.6 版
> 
> PR 入面唔應該更新版本號，發佈嗰陣我嚟更新

明嘞，所以而家就係要拆成幾個PR嚟改

2021-12-07 17:08 UTC, graphemecluster commented
應該做個 benchmark，睇下咩方法快啲

2021-12-07 17:11 UTC, hfhchan commented on content_scripts/main.js
> +    return reHan.test(s);
\p{Script=Han} backcompat 到邊個版本，嚟緊仲有 CJK Extension G… 自己寫 regex perf 又點… 呢啲有冇測過？

2021-12-07 19:41 UTC, ayaka14732 commented on content_scripts/main.js
> +    return reHan.test(s);
呢排啱好寫咗篇文講 `\p{Script=Han}`：[How to Properly Match Chinese Characters With Regular Expression](https://ayaka.shn.hk/hanregex/)

2021-12-08 02:53 UTC, graphemecluster commented
Benchmark:
```js
function traverse(array, current) {
    if (["RUBY", "OPTION", "TEXTAREA", "SCRIPT", "STYLE"].includes(current.tagName)) {
        return;
    }
    for (const node of current.childNodes) {
        if (node.nodeType === Node.TEXT_NODE) {
            array.push(node);
        } else {
            traverse(array, node);
        }
    }
}

new Benchmark.Suite()
    .add("Custom traverse function", function () {
        const array = [];
        traverse(array, document.body);
    })
    .add("NodeIterator with filter function", function () {
        const nodeIterator = document.createNodeIterator(document.body, NodeFilter.SHOW_TEXT, {
            acceptNode(node) {
                if (["RUBY", "OPTION", "TEXTAREA", "SCRIPT", "STYLE"].includes(node.tagName)) {
                    return NodeFilter.FILTER_REJECT;
                }
                return NodeFilter.FILTER_ACCEPT;
            },
        });
        const array = [];
        let current;
        while ((current = nodeIterator.nextNode())) array.push(current);
    })
    .add("TreeWalker with filter function", function () {
        const treeWalker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
            acceptNode(node) {
                if (["RUBY", "OPTION", "TEXTAREA", "SCRIPT", "STYLE"].includes(node.tagName)) {
                    return NodeFilter.FILTER_REJECT;
                }
                return NodeFilter.FILTER_ACCEPT;
            },
        });
        const array = [];
        let current;
        while ((current = treeWalker.nextNode())) array.push(current);
    })
    .add("TreeWalker traverse function", function () {
        const treeWalker = document.createTreeWalker(document.body);
        const array = [];
        let current = treeWalker.nextNode();
        do {
            if (["RUBY", "OPTION", "TEXTAREA", "SCRIPT", "STYLE"].includes(current.tagName)) {
                do {
                    current = treeWalker.nextSibling();
                    if (current) break;
                    current = treeWalker.parentNode();
                } while (current);
            } else {
                if (current.nodeType === Node.TEXT_NODE) {
                    array.push(current);
                }
                current = treeWalker.nextNode();
            }
        } while (current);
    })
    .on("cycle", function (event) {
        console.log(event.target + "");
    })
    .on("complete", function () {
        console.log("The fastest is " + this.filter("fastest").map("name"));
    })
    .run({ async: true });
```
頭 3 個嘅速度幾乎一樣，最後一個嘅速度係前面嗰啲嘅大概 3 倍半。
但係兩個 traverse function 嘅結果似乎同兩個 filter function 有啲唔同……

2021-12-08 02:56 UTC, graphemecluster commented on content_scripts/main.js
> +    if (['RUBY', 'RP', 'RT', 'OPTION', 'TEXTAREA', 'SCRIPT', 'STYLE'].includes(node.parentNode.nodeName)) {
噉樣寫嘅話如果 `rt` 入面有個 `b` 就會出事，所以一定要遞迴檢測，或者用下面 benchmark 嘅方法

2021-12-08 03:19 UTC, ambar commented on content_scripts/main.js
> +    return reHan.test(s);
感谢解释，看起来是用了 Script=Han 子集，虽然结果没影响。现已去掉了这个 regexp 替换。

2021-12-08 04:31 UTC, ambar commented on content_scripts/main.js
> +    if (['RUBY', 'RP', 'RT', 'OPTION', 'TEXTAREA', 'SCRIPT', 'STYLE'].includes(node.parentNode.nodeName)) {
感谢指出，没考虑 rt 下可以有任意元素。

我最开始有测试过遍历文本，不指定 filter function 是最快的（一个数量级）：

https://codesandbox.io/s/treewalker-perf-i9125?file=/bench.js

```
recursive x 3,581 ops/sec ±0.62% (67 runs sampled)
treeWalker x 21,017 ops/sec ±2.42% (64 runs sampled)
treeWalkerWithFilterFunction x 2,917 ops/sec ±0.52% (19 runs sampled)
Fastest is treeWalker
```

如果有可靠过滤掉 ruby，另外的可考虑变通办法是 `closest("ruby")`，仍略快于 recursive 方式：

https://codesandbox.io/s/treewalker-perf-forked-l79ud?file=/bench.js

```
recursive x 3,439 ops/sec ±0.62% (68 runs sampled)
treeWalker x 4,814 ops/sec ±0.82% (67 runs sampled)
treeWalkerWithFilterFunction x 1,971 ops/sec ±0.34% (67 runs sampled)
Fastest is treeWalker
```

2021-12-08 04:45 UTC, laubonghaudoi commented on content_scripts/main.js
> +    return reHan.test(s);
> 

呢篇嘢好正。噉所以而家就係確定咗自動標所有漢字？

2021-12-09 13:55 UTC, laubonghaudoi commented
@graphemecluster 我冇睇明個 benchmark，説明咗乜？

2021-12-10 04:22 UTC, ambar commented
由于 最终 treeWalker  优势不明显，revert 了。lang 处理也保留了 —— 但它的处理也会带来不利的地方，在 MutationObserver 中需要向上查找。

2021-12-10 17:24 UTC, ayaka14732 commented
> 而且我哋仲未考慮 `lang` 屬性，到頭來係咪用返原先嘅方法唔郁段 code 最好要問下 @ayaka14732 嘅意見。

我冇意見，不如交畀你決定啦～

2021-12-12 03:22 UTC, alex-the-man commented
請問呢個PR fix咗邊幾個cases？係唔係AJAX load嘅context？可以麻煩你俾幾個websites做例子嗎？

我哋搵lihkg.com試，AJAX load嘅content依然inject唔到。請問呢個fix本身應唔應該fix埋呢個case？

2021-12-12 03:49 UTC, graphemecluster commented
係我搞錯咗啲嘢，唔好意思
![LIHKG](https://user-images.githubusercontent.com/53967830/145699480-06581ed3-0e86-4c95-8613-4a94000f54f8.png)

2021-12-12 04:27 UTC, laubonghaudoi approved these changes

2021-12-12 04:49 UTC, merged